### Signup a User
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "user_e@e.com",
    "password": "user_e",
    "is_admin": true
}


### Signin User
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "user_e@e.com",
    "password": "user_e"
}