### Signup a User
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "d@d.com",
    "password": "d",
    "is_admin": true
}


### Signin User
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "username": "d@d.com",
    "password": "d"
}


### Protect Route whoiam
GET http://localhost:3000/users/whoiam
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRAZC5jb20iLCJ1c2VyX2lkIjo3LCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjY2MTkyNzM2LCJleHAiOjE2NjYyMDcxMzZ9.qBVSlnBSfKcZGXlhoO_gd9VB1N3enYN5Bn5pp_38nvw
