### Get Posts
GET http://localhost:3000/posts
Content-Type: application/json


### Get Post By Id
GET http://localhost:3000/posts/5
Content-Type: application/json


### Create a Post
POST http://localhost:3000/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJzdXBlcmFkbWluQGhvbWUuY29tIiwidXNlcl9pZCI6MSwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTY2Njg3ODg5MCwiZXhwIjoxNjY2ODkzMjkwfQ.F3x-uQsPFjBShgW2uGzFPlONfyG4aIti2cTeFgcMP4g

{
    "title": "new_a2",
    "content": {
        "blocks" : [
            {
                "id" : "ybzChKQzG9",
                "type" : "header",
                "data" : {
                    "text" : "Editor.js",
                    "level" : 2
                }
            }
        ]
    },
    "category_name": ["Design"]
}
