### Get Posts
GET http://localhost:3010/posts
Content-Type: application/json


### Get Post By Id
GET http://localhost:3010/posts/2
Content-Type: application/json


### Create a Post
POST http://localhost:3010/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJzdXBlcmFkbWluQGhvbWUuY29tIiwidXNlcl9pZCI6MSwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTY2NzMxODY0MSwiZXhwIjoxNjY3MzMzMDQxfQ.Ax78cuUgfr1RQDTiJLKLrHfqv___wzIxs9Axtmbt660

{
    "title": "Javscript is the best",
    "content": {
        "blocks" : [
            {
                "id" : "ybzChKQzG9",
                "type" : "header",
                "data" : {
                    "text" : "Editor.js",
                    "level" : 2
                }
            }
        ]
    },
    "category_name": ["Javascript", "NodeJS"]
}
